name = "filesystem"
main = "src/index.ts"
compatibility_date = "2023-10-30"

account_id = "d6bb759ee03e071575964565d63b7c4a" # â† Replace with your Account ID.
workers_dev = true

[[r2_buckets]]
binding = 'Yaqeen' # <~ valid JavaScript variable name
bucket_name = 'yaqeen'

[placement]
mode = "smart"
